USE [master]
GO

/****** Object:  Database [StorexWebDatabase]    Script Date: 8/11/2022 10:35:03 AM ******/
CREATE DATABASE [StorexWebDatabase]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'StorexWebDatabase', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER01\MSSQL\DATA\StorexWebDatabase.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'StorexWebDatabase_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER01\MSSQL\DATA\StorexWebDatabase_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [StorexWebDatabase].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [StorexWebDatabase] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [StorexWebDatabase] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [StorexWebDatabase] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [StorexWebDatabase] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [StorexWebDatabase] SET ARITHABORT OFF 
GO

ALTER DATABASE [StorexWebDatabase] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [StorexWebDatabase] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [StorexWebDatabase] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [StorexWebDatabase] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [StorexWebDatabase] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [StorexWebDatabase] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [StorexWebDatabase] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [StorexWebDatabase] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [StorexWebDatabase] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [StorexWebDatabase] SET  DISABLE_BROKER 
GO

ALTER DATABASE [StorexWebDatabase] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [StorexWebDatabase] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [StorexWebDatabase] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [StorexWebDatabase] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [StorexWebDatabase] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [StorexWebDatabase] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [StorexWebDatabase] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [StorexWebDatabase] SET RECOVERY FULL 
GO

ALTER DATABASE [StorexWebDatabase] SET  MULTI_USER 
GO

ALTER DATABASE [StorexWebDatabase] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [StorexWebDatabase] SET DB_CHAINING OFF 
GO

ALTER DATABASE [StorexWebDatabase] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [StorexWebDatabase] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [StorexWebDatabase] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [StorexWebDatabase] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [StorexWebDatabase] SET QUERY_STORE = OFF
GO

ALTER DATABASE [StorexWebDatabase] SET  READ_WRITE 
GO

